# Generated by Django 5.0.6 on 2024-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=200)),
                ('dimension1', models.FloatField(blank=True, null=True)),
                ('dimension2', models.FloatField(blank=True, null=True)),
                ('dimension3', models.FloatField(blank=True, null=True)),
                ('supplier_art', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
